GET http://localhost:3000/meals
###
GET http://localhost:3000/meals/6652163d837140a757175035 
###
GET http://localhost:3000/meals/6634fe9719b1813c43b3f959 
###
GET http://localhost:3000/meals/6634fec619b1813c43b3f95a
###
POST http://localhost:3000/meals/
content-type: application/json

{
    "name": "Pizza",
    "recipeId": "None",
    "rating": "5"
}
###
PUT http://localhost:3000/meals/6652163d837140a757175035
content-type: application/json

{
    "name": "Pasta",
    "recipeId": "None",
    "rating": "3"
}
###
DELETE  http://localhost:3000/meals/663e906d005ba026e26ed524


### render requests
GET https://meal-tracker-bros.onrender.com/meals
###
GET https://meal-tracker-bros.onrender.com/meals/6652163d837140a757175035 
###
POST https://meal-tracker-bros.onrender.com/meals/
content-type: application/json

{
    "name": "Pasta",
    "recipeId": "None",
    "rating": "5"
}
###
PUT https://meal-tracker-bros.onrender.com/meals/663eeec55908891a038eb8b3
content-type: application/json

{
    "name": "Pasta",
    "recipeId": "None",
    "rating": "3"
}
###
DELETE  https://meal-tracker-bros.onrender.com/meals/6651fbd65583d70d6cf9ba71